import type { PopupLanguageOption, UserSettings } from './types';

export const STORAGE_KEY = 'ytDualSubSettings';

export const DEFAULT_SETTINGS: UserSettings = {
  enabled: true,
  targetLanguage: 'fa',
  showOriginal: true,
  showTranslated: true,
  layout: 'column',
  gapPx: 8,
  originalFontSizePx: 26,
  translatedFontSizePx: 28,
  originalColor: '#ffffff',
  translatedColor: '#ffd54f',
  backgroundColor: 'rgba(0, 0, 0, 0.55)',
  bottomOffsetPx: 72,
  paddingPx: 10,
  borderRadiusPx: 12,
  maxWidthPercent: 82,
  fontFamily: 'Arial, Tahoma, sans-serif',
  hideNativeSubtitles: true,
  textAlign: 'center',
};

export const SUPPORTED_LANGUAGES: PopupLanguageOption[] = [
  { code: 'fa', label: 'Persian (فارسی)' },
  { code: 'en', label: 'English' },
  { code: 'de', label: 'German (Deutsch)' },
  { code: 'fr', label: 'French (Français)' },
  { code: 'es', label: 'Spanish (Español)' },
  { code: 'it', label: 'Italian (Italiano)' },
  { code: 'pt', label: 'Portuguese (Português)' },
  { code: 'ru', label: 'Russian (Русский)' },
  { code: 'ar', label: 'Arabic (العربية)' },
  { code: 'tr', label: 'Turkish (Türkçe)' },
  { code: 'nl', label: 'Dutch (Nederlands)' },
  { code: 'sv', label: 'Swedish (Svenska)' },
  { code: 'pl', label: 'Polish (Polski)' },
  { code: 'uk', label: 'Ukrainian (Українська)' },
  { code: 'hi', label: 'Hindi (हिन्दी)' },
  { code: 'ur', label: 'Urdu (اردو)' },
  { code: 'ja', label: 'Japanese (日本語)' },
  { code: 'ko', label: 'Korean (한국어)' },
  { code: 'zh-Hans', label: 'Chinese Simplified (简体中文)' },
  { code: 'zh-Hant', label: 'Chinese Traditional (繁體中文)' },
  { code: 'id', label: 'Indonesian (Bahasa Indonesia)' },
  { code: 'ms', label: 'Malay (Bahasa Melayu)' },
  { code: 'vi', label: 'Vietnamese (Tiếng Việt)' },
  { code: 'th', label: 'Thai (ไทย)' },
  { code: 'he', label: 'Hebrew (עברית)' },
  { code: 'el', label: 'Greek (Ελληνικά)' },
  { code: 'ro', label: 'Romanian (Română)' },
  { code: 'cs', label: 'Czech (Čeština)' },
  { code: 'hu', label: 'Hungarian (Magyar)' },
  { code: 'bn', label: 'Bengali (বাংলা)' },
];