export type LayoutMode = 'column' | 'row';

export type SubtitleCue = {
  startMs: number;
  endMs: number;
  text: string;
};

export type SubtitleTrack = {
  baseUrl: string;
  languageCode: string;
  languageName: string;
  vssId?: string;
  kind?: string;
  isTranslatable: boolean;
  isAutoGenerated: boolean;
};

export type UserSettings = {
  enabled: boolean;
  targetLanguage: string;
  showOriginal: boolean;
  showTranslated: boolean;
  layout: LayoutMode;
  gapPx: number;
  originalFontSizePx: number;
  translatedFontSizePx: number;
  originalColor: string;
  translatedColor: string;
  backgroundColor: string;
  bottomOffsetPx: number;
  paddingPx: number;
  borderRadiusPx: number;
  maxWidthPercent: number;
  fontFamily: string;
  hideNativeSubtitles: boolean;
  textAlign: 'center' | 'left' | 'right';
};

export type PageBridgeTrack = {
  baseUrl: string;
  languageCode: string;
  languageName: string;
  vssId?: string;
  kind?: string;
  isTranslatable: boolean;
};

export type BridgeState = {
  url: string;
  videoId: string | null;
  currentTimeSec: number;
  captionsEnabled: boolean;
  selectedTrack: PageBridgeTrack | null;
  captionTracks: PageBridgeTrack[];
};

export type BridgeStateEventDetail = {
  state: BridgeState;
};

export type PopupLanguageOption = {
  code: string;
  label: string;
};