import type { PageBridgeTrack, SubtitleCue, SubtitleTrack } from '../shared/types';

const LOG_PREFIX = '[YT Dual Sub][captions]';

type Json3Event = {
  tStartMs?: number;
  dDurationMs?: number;
  segs?: Array<{ utf8?: string }>;
};

type Json3Response = {
  events?: Json3Event[];
};

export function normalizeTrack(track: PageBridgeTrack): SubtitleTrack {
  const normalized = {
    baseUrl: track.baseUrl,
    languageCode: track.languageCode,
    languageName: track.languageName,
    vssId: track.vssId,
    kind: track.kind,
    isTranslatable: track.isTranslatable,
    isAutoGenerated: Boolean(track.kind?.includes('asr')),
  };

  console.log(`${LOG_PREFIX} normalizeTrack`, normalized);
  return normalized;
}

export function buildTranslatedTrackUrl(
  baseUrl: string,
  targetLanguage: string,
): string {
  const url = new URL(baseUrl, window.location.origin);
  url.searchParams.set('fmt', 'json3');
  url.searchParams.set('tlang', targetLanguage);
  const finalUrl = url.toString();
  console.log(`${LOG_PREFIX} buildTranslatedTrackUrl`, {
    targetLanguage,
    finalUrl,
  });
  return finalUrl;
}

export function buildOriginalTrackUrl(baseUrl: string): string {
  const url = new URL(baseUrl, window.location.origin);
  url.searchParams.set('fmt', 'json3');
  url.searchParams.delete('tlang');
  const finalUrl = url.toString();
  console.log(`${LOG_PREFIX} buildOriginalTrackUrl`, { finalUrl });
  return finalUrl;
}

export async function fetchSubtitleCues(url: string): Promise<SubtitleCue[]> {
  console.log(`${LOG_PREFIX} fetchSubtitleCues:start`, { url });
  const response = await fetch(url, {
    credentials: 'include',
  });

  console.log(`${LOG_PREFIX} fetchSubtitleCues:response`, {
    url,
    ok: response.ok,
    status: response.status,
  });

  if (!response.ok) {
    throw new Error(`Subtitle fetch failed: ${response.status}`);
  }

  const data = (await response.json()) as Json3Response;
  const cues = parseJson3ToCues(data);
  console.log(`${LOG_PREFIX} fetchSubtitleCues:done`, {
    url,
    cues: cues.length,
  });
  return cues;
}

export function parseJson3ToCues(data: Json3Response): SubtitleCue[] {
  const events = data.events ?? [];
  const cues: SubtitleCue[] = [];

  console.log(`${LOG_PREFIX} parseJson3ToCues:start`, {
    events: events.length,
  });

  for (const event of events) {
    if (event.tStartMs == null || event.dDurationMs == null) continue;
    if (!event.segs?.length) continue;

    const text = event.segs
      .map((seg) => seg.utf8 ?? '')
      .join('')
      .replace(/\n{3,}/g, '\n\n')
      .trim();

    if (!text) continue;

    cues.push({
      startMs: event.tStartMs,
      endMs: event.tStartMs + event.dDurationMs,
      text,
    });
  }

  const merged = mergeAdjacentDuplicateCues(cues);
  console.log(`${LOG_PREFIX} parseJson3ToCues:done`, {
    rawCues: cues.length,
    mergedCues: merged.length,
  });
  return merged;
}

function mergeAdjacentDuplicateCues(cues: SubtitleCue[]): SubtitleCue[] {
  if (cues.length <= 1) return cues;

  const merged: SubtitleCue[] = [cues[0]];

  for (let i = 1; i < cues.length; i += 1) {
    const current = cues[i];
    const previous = merged[merged.length - 1];

    if (current.text === previous.text && current.startMs <= previous.endMs + 50) {
      previous.endMs = current.endMs;
      continue;
    }

    merged.push({ ...current });
  }

  if (merged.length !== cues.length) {
    console.log(`${LOG_PREFIX} mergeAdjacentDuplicateCues:collapsed`, {
      before: cues.length,
      after: merged.length,
    });
  }

  return merged;
}