import type {
  PageBridgeTrack,
  SubtitleCue,
  SubtitleTrack,
} from "../shared/types";

const LOG_PREFIX = "[YT Dual Sub][captions]";

export type SubtitleFetchOutcome = {
  cues: SubtitleCue[];
  emptyReason: "empty-body" | "parsed-empty" | "blocked-html" | null;
};

type Json3Event = {
  tStartMs?: number;
  dDurationMs?: number;
  segs?: Array<{ utf8?: string }>;
};

type Json3Response = {
  events?: Json3Event[];
};

function decodeHtml(text: string): string {
  const textarea = document.createElement("textarea");
  textarea.innerHTML = text;
  return textarea.value;
}

export function normalizeTrack(track: PageBridgeTrack): SubtitleTrack {
  const normalized = {
    baseUrl: track.baseUrl,
    languageCode: track.languageCode,
    languageName: track.languageName,
    vssId: track.vssId,
    kind: track.kind,
    isTranslatable: track.isTranslatable,
    isAutoGenerated: Boolean(track.kind?.includes("asr")),
  };

  console.log(`${LOG_PREFIX} normalizeTrack`, normalized);
  return normalized;
}

function toAbsoluteYoutubeUrl(baseUrl: string): URL {
  return new URL(baseUrl, "https://www.youtube.com");
}

function isBlockedHtmlResponse(body: string): boolean {
  const trimmed = body.trim();

  if (!trimmed.startsWith("<")) return false;

  if (/^<html[\s\S]*<body>\s*<\/body>\s*<\/html>$/i.test(trimmed)) {
    return true;
  }

  if (/Sorry\.\.\./i.test(trimmed)) {
    return true;
  }

  if (/unusual traffic/i.test(trimmed)) {
    return true;
  }

  return false;
}

export function buildTranslatedTrackUrl(
  baseUrl: string,
  targetLanguage: string,
): string {
  const url = toAbsoluteYoutubeUrl(baseUrl);

  if (!url.searchParams.has("fmt")) {
    url.searchParams.set("fmt", "json3");
  }

  url.searchParams.set("tlang", targetLanguage);

  const finalUrl = url.toString();

  console.log(`${LOG_PREFIX} buildTranslatedTrackUrl`, {
    targetLanguage,
    finalUrl,
  });

  return finalUrl;
}

export function buildOriginalTrackUrl(baseUrl: string): string {
  const url = toAbsoluteYoutubeUrl(baseUrl);

  if (!url.searchParams.has("fmt")) {
    url.searchParams.set("fmt", "json3");
  }

  url.searchParams.delete("tlang");

  const finalUrl = url.toString();
  const preservedParams: string[] = [];
  url.searchParams.forEach((_, key) => {
    preservedParams.push(key);
  });

  console.log(`${LOG_PREFIX} buildOriginalTrackUrl`, {
    finalUrl,
    preservedParams,
  });

  return finalUrl;
}

export async function fetchSubtitleCues(
  url: string,
): Promise<SubtitleFetchOutcome> {
  console.log(`${LOG_PREFIX} fetchSubtitleCues:start`, { url });
  const response = await fetch(url, {
    method: "GET",
    credentials: "include",
    cache: "no-store",
  });

  console.log(`${LOG_PREFIX} fetchSubtitleCues:response`, {
    url,
    ok: response.ok,
    status: response.status,
  });

  const rawBody = await response.text();

  if (response.status === 429) {
    throw new Error("Subtitle fetch rate limited: 429");
  }

  if (!response.ok) {
    throw new Error(`Subtitle fetch failed: ${response.status}`);
  }

  console.log(`${LOG_PREFIX} fetchSubtitleCues:result`, {
    url,
    status: response.status,
    ok: response.ok,
    contentType: response.headers.get("content-type"),
    rawLength: rawBody.length,
    preview: rawBody.slice(0, 300),
  });

  if (!rawBody.trim()) {
    console.warn(`${LOG_PREFIX} fetchSubtitleCues:empty response body`, {
      url,
    });
    return {
      cues: [],
      emptyReason: "empty-body",
    };
  }

  if (isBlockedHtmlResponse(rawBody)) {
    console.warn(`${LOG_PREFIX} fetchSubtitleCues:blocked html response`, {
      url,
      status: response.status,
      contentType: response.headers.get("content-type"),
      preview: rawBody.slice(0, 240),
    });

    return {
      cues: [],
      emptyReason: "blocked-html",
    };
  }

  const parsed = parseSubtitleResponse(rawBody);
  if (!parsed.length) {
    console.warn(`${LOG_PREFIX} fetchSubtitleCues:parsed empty cues`, {
      url,
      bodyPreview: rawBody.slice(0, 180),
    });
  }

  const cues = mergeAdjacentDuplicateCues(parsed);
  console.log(`${LOG_PREFIX} fetchSubtitleCues:done`, {
    url,
    cues: cues.length,
  });
  return {
    cues,
    emptyReason: cues.length ? null : "parsed-empty",
  };
}

function parseSubtitleResponse(rawBody: string): SubtitleCue[] {
  const body = rawBody.trim();

  if (body.startsWith("{")) {
    try {
      const data = JSON.parse(body) as Json3Response;
      return parseJson3ToCues(data);
    } catch (error) {
      console.warn(
        `${LOG_PREFIX} parseSubtitleResponse:json parse failed`,
        error,
      );
      return [];
    }
  }

  if (body.startsWith("<")) {
    return parseXmlToCues(body);
  }

  return [];
}

function parseXmlToCues(xmlText: string): SubtitleCue[] {
  const parser = new DOMParser();
  const doc = parser.parseFromString(xmlText, "text/xml");
  if (doc.querySelector("parsererror")) {
    console.warn(`${LOG_PREFIX} parseXmlToCues:invalid XML`);
    return [];
  }

  const textNodes = Array.from(doc.querySelectorAll("text"));
  const paragraphNodes = Array.from(doc.querySelectorAll("p"));
  const cues: SubtitleCue[] = [];

  for (const node of textNodes) {
    const start = Number(node.getAttribute("start"));
    const dur = Number(node.getAttribute("dur"));

    if (!Number.isFinite(start) || !Number.isFinite(dur)) continue;

    const text = decodeHtml(node.textContent ?? "")
      .replace(/\n{3,}/g, "\n\n")
      .trim();

    if (!text) continue;

    cues.push({
      startMs: Math.round(start * 1000),
      endMs: Math.round((start + dur) * 1000),
      text,
    });
  }

  for (const node of paragraphNodes) {
    const startMs = Number(node.getAttribute("t"));
    const durationMs = Number(node.getAttribute("d"));

    if (!Number.isFinite(startMs) || !Number.isFinite(durationMs)) continue;

    const segmentNodes = Array.from(node.querySelectorAll("s"));
    const rawText = segmentNodes.length
      ? segmentNodes.map((segment) => segment.textContent ?? "").join("")
      : (node.textContent ?? "");

    const text = decodeHtml(rawText)
      .replace(/\n{3,}/g, "\n\n")
      .trim();

    if (!text) continue;

    cues.push({
      startMs: Math.round(startMs),
      endMs: Math.round(startMs + durationMs),
      text,
    });
  }

  cues.sort((a, b) => a.startMs - b.startMs);

  console.log(`${LOG_PREFIX} parseXmlToCues`, {
    textNodes: textNodes.length,
    paragraphNodes: paragraphNodes.length,
    cues: cues.length,
  });

  return cues;
}

export function parseJson3ToCues(data: Json3Response): SubtitleCue[] {
  const events = data.events ?? [];
  const cues: SubtitleCue[] = [];

  console.log(`${LOG_PREFIX} parseJson3ToCues:start`, {
    events: events.length,
  });

  for (const event of events) {
    if (event.tStartMs == null || event.dDurationMs == null) continue;
    if (!event.segs?.length) continue;

    const text = event.segs
      .map((seg) => seg.utf8 ?? "")
      .join("")
      .replace(/\u200b/g, "")
      .trim();

    const decodedText = decodeHtml(text)
      .replace(/\n{3,}/g, "\n\n")
      .trim();

    if (!decodedText) continue;

    cues.push({
      startMs: event.tStartMs,
      endMs: event.tStartMs + event.dDurationMs,
      text: decodedText,
    });
  }

  console.log(`${LOG_PREFIX} parseJson3ToCues:done`, {
    rawCues: cues.length,
    mergedCues: cues.length,
  });
  return cues;
}

function mergeAdjacentDuplicateCues(cues: SubtitleCue[]): SubtitleCue[] {
  if (cues.length <= 1) return cues;

  const merged: SubtitleCue[] = [cues[0]];

  for (let i = 1; i < cues.length; i += 1) {
    const current = cues[i];
    const previous = merged[merged.length - 1];

    if (
      current.text === previous.text &&
      current.startMs <= previous.endMs + 50
    ) {
      previous.endMs = current.endMs;
      continue;
    }

    merged.push({ ...current });
  }

  if (merged.length !== cues.length) {
    console.log(`${LOG_PREFIX} mergeAdjacentDuplicateCues:collapsed`, {
      before: cues.length,
      after: merged.length,
    });
  }

  return merged;
}
